name: 'Build CI FE A1-Platform code'
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Docker build & push image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout employee-assessment-fe
        uses: actions/checkout@main
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          repository: a1lplatform/employee-assessment-fe
      -
        name: Checkout a1-platform-fe
        uses: actions/checkout@master
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          repository: phillipsho/a1-platform-fe
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/a1platformfe:latest
