name: 'Build CI FE A1-Platform code'
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Docker build & push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  
        with:
          repository: a1lplatform/employee-assessment-fe
          token: ${{ secrets.PRIVATE_SSH_KEY }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/a1platformfe:latest